<?php

use Drupal\Core\Template\Attribute;

function horoscope_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'horoscope/horoscope';
}

/**
 * Implements hook_theme_registry_alter
 */
function horoscope_theme_registry_alter(&$theme_registry) {
    $theme_registry['views_view_unformatted__horoscope__horoscope_daily'] = $theme_registry['views_view_unformatted'];
    $theme_registry['views_view_unformatted__horoscope__horoscope_daily']['template'] = 'views-view-unformatted--horoscope--horoscope-daily';
    $theme_registry['views_view_unformatted__horoscope__horoscope_daily']['path'] = drupal_get_path('module', 'horoscope') . '/templates/views';
    $theme_registry['views_view_unformatted__horoscope__horoscope_weekly'] = $theme_registry['views_view_unformatted'];
    $theme_registry['views_view_unformatted__horoscope__horoscope_weekly']['template'] = 'views-view-unformatted--horoscope--horoscope-weekly';
    $theme_registry['views_view_unformatted__horoscope__horoscope_weekly']['path'] = drupal_get_path('module', 'horoscope') . '/templates/views';
    $theme_registry['views_view_unformatted__horoscope__horoscope_monthly'] = $theme_registry['views_view_unformatted'];
    $theme_registry['views_view_unformatted__horoscope__horoscope_monthly']['template'] = 'views-view-unformatted--horoscope--horoscope-monthly';
    $theme_registry['views_view_unformatted__horoscope__horoscope_monthly']['path'] = drupal_get_path('module', 'horoscope') . '/templates/views';
}

/**
 * @param $variables
 */
function horoscope_preprocess_views_view_unformatted(&$variables) {
    global $base_root, $base_path;
    $variables['aries_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/aries.jpg';
    $variables['taurus_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/taurus.jpg';
    $variables['gemini_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/gemini.jpg';
    $variables['cancer_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/cancer.jpg';
    $variables['leo_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/leo.jpg';
    $variables['virgo_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/virgo.jpg';
    $variables['libra_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/libra.jpg';
    $variables['scorpio_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/scorpio.jpg';
    $variables['sagittarius_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/sagittarius.jpg';
    $variables['capricorn_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/capricorn.jpg';
    $variables['aquarius_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/aquarius.jpg';
    $variables['pisces_ico'] = $base_root . $base_path . drupal_get_path('module', 'horoscope') . '/icons/pisces.jpg';

    $variables['horoscope_day'] = format_date(time(), 'custom', 'Y-m-d');
    $variables['horoscope_month_text'] = format_date(time(), 'custom', 'F');
}

